# docker-compose version
version: '3.8'
services:
  xxl-job-admin:
    # 4、调度中心本地Build设置，如果期望使用推动DockerHub的镜像，可以注释当前启用的image、build配置，并启用如下设置版本的image配置；
    build:
      context: ./xxl-job-admin
      dockerfile: Dockerfile
    container_name: xxl-job
    environment:
      # 5、数据库密码设置，需要与application-prod中保持一致：
      - TZ=Asia/Shanghai
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=tomori
      - DB_DATABASE=xxl_job
    ports:
      - "8077:8080"
    # 加入自定义网络
    networks:
      - dshiq04
# 加入自定义网络
networks:
  dshiq04:
    external: true